export const HANDLE_LOGIN = 'HANDLE_LOGIN';
export const HANDLE_LOGIN_SUCCESS = 'HANDLE_LOGIN_SUCCESS';
export const HANDLE_FETCH_SCHOOLS = 'HANDLE_FETCH_SCHOOLS';
export const HANDLE_FETCH_SCHOOLS_SUCCESS = 'HANDLE_FETCH_SCHOOLS_SUCCESS';
