// login action
export const HANDLE_LOGIN = 'HANDLE_LOGIN';
export const HANDLE_LOGIN_SUCCESS = 'HANDLE_LOGIN_SUCCESS';
export const HANDLE_LOGOUT_SUCCESS = 'HANDLE_LOGOUT_SUCCESS'


// fetch schools
export const HANDLE_FETCH_SCHOOLS = 'HANDLE_FETCH_SCHOOLS';
export const HANDLE_FETCH_SCHOOLS_SUCCESS = 'HANDLE_FETCH_SCHOOLS_SUCCESS';
export const HANDLE_ADD_SCHOOL = 'HANDLE_ADD_SCHOOL';
export const HANDLE_ADD_SCHOOL_SUCCESS = 'HANDLE_ADD_SCHOOL_SUCCESS';


// fetch students
export const HANDLE_FETCH_STUDENTS = 'HANDLE_FETCH_STUDENTS';
export const HANDLE_FETCH_STUDENTS_SUCCESS = 'HANDLE_FETCH_STUDENTS_SUCCESS';
export const HANDLE_FETCH_STUDENTS_FAIL = 'HANDLE_FETCH_STUDENTS_FAIL';


// fetch classes
export const HANDLE_FETCH_CLASSES = 'HANDLE_FETCH_CLASSES';
export const HANDLE_FETCH_CLASSES_SUCCESS = 'HANDLE_FETCH_CLASSES_SUCCESS';


// fetch Teachers
export const HANDLE_FETCH_TEACHERS = 'HANDLE_FETCH_TEACHERS';
export const HANDLE_FETCH_TEACHERS_SUCCESS = 'HANDLE_FETCH_TEACHERS_SUCCESS';

export const HANDLE_ADD_TEACHERS = 'HANDLE_ADD_TEACHER';
export const HANDLE_ADD_TEACHERS_SUCCESS = 'HANDLE_ADD_TEACHER_SUCCESS';

//Lesson Plans
export const HANDLE_FETCH_LESSONPLAN = 'HANDLE_FETCH_LESSONPLAN'
export const HANDLE_FETCH_LESSONPLAN_SUCCESS = 'HANDLE_FETCH_LESSONPLAN_SUCCESS'
export const HANDLE_ADD_LESSONPLAN = 'HANDLE_ADD_LESSONPLAN';
export const HANDLE_ADD_LESSONPLAN_SUCCESS = 'HANDLE_ADD_LESSONPLAN_SUCCESS';


//Assignments
export const HANDLE_FETCH_ASSIGNMENT = 'HANDLE_FETCH_ASSIGNMENT'
export const HANDLE_FETCH_ASSIGNMENT_SUCCESS = 'HANDLE_FETCH_ASSIGNMENT_SUCCESS'
export const HANDLE_ADD_ASSIGNMENT = 'HANDLE_ADD_ASSIGNMENT';
export const HANDLE_ADD_ASSIGNMENT_SUCCESS = 'HANDLE_ADD_ASSIGNMENT_SUCCESS';

//terms
export const HANDLE_FETCH_TERM = 'HANDLE_FETCH_TERM'
export const HANDLE_FETCH_TERM_SUCCESS = 'HANDLE_FETCH_TERM_SUCCESS'
export const HANDLE_FETCH_TERM_FAIL = 'HANDLE_FETCH_TERM_FAIL'
export const HANDLE_UPDATE_TERM  = 'HANDLE_UPDATE_TERM'
export const HANDLE_UPDATE_TERM_SUCCESS  = 'HANDLE_UPDATE_TERM_SUCCESS'

//question
export const HANDLE_FETCH_QUESTION = 'HANDLE_FETCH_QUESTION'
export const HANDLE_FETCH_QUESTION_SUCCESS = 'HANDLE_FETCH_QUESTION_SUCCESS'
export const HANDLE_FETCH_QUESTION_FAIL = 'HANDLE_FETCH_QUESTION_FAIL'
export const HANDLE_ADD_QUESTION = 'HANDLE_ADD_QUESTION';
export const HANDLE_ADD_QUESTION_SUCCESS = 'HANDLE_ADD_QUESTION_SUCCESS';